### PR TITLE
Changes in filestructure

### PR DESCRIPTION
**Pull request by sadaf2605**
When we have started to work on multiple features I think we should have a common entry point from where we can access, different methods and functions for different commands (eg: $ nntoolkit evaluate ..., $ nntoolkit train ...). So I made `nntoolkit.py`, right now the only thing it does is, it handles commands, later we can add more common trait of features (like file parsing) in it. I am sure that this structure will help us, when our project will grow bigger with more contributors.

Let me help you with the conflicts:
-Setup.py: made the entry point to nntoolkit.py.
-nntoolkit.py: copy paste from evaluate.py.
-evaluate.py: deleted copied lines.
-input.vec: a file with bunch of zeros for testing '-i input.vec' command.

[I think next time I would ask before working on something, this time I just did it :/ let me know if you think I am making the code structure looks too much like java-ish (in a bad way), and I may have messed up with git this time, let me know if some part do not work because of it.]

### CODE REVIEW

**Comment by MartinThoma** [comment]
Have you seen [nntoolkit/bin/nntoolkit](https://github.com/MartinThoma/nntoolkit/blob/master/bin/nntoolkit) and [nntoolkit/nntoolkit/utils.py](https://github.com/MartinThoma/nntoolkit/blob/master/nntoolkit/utils.py)?

The Python script `nntoolkit` is the entry point for the command line interface whereas common functionality, which gets used in multiple modules, should be placed in `utils.py`.

**Comment by sadaf2605** [comment]
In that case we can remove <code>ntoolkit.py</code> file and add the code of it to <code>utils.py</code>.

**Comment by sadaf2605** [comment]
I can send another commit, if you want it that way. 

[Or we can copy the code of <code>utils.py</code> to <code>nntoolkit.py</code> which does not sound appropriate]

**Comment by MartinThoma** [comment]
You seem to have removed `get_parser()` from `nntoolkit/evaluate.py`. This is not good, because every tool should have this method so that `bin/nntoolkit` can call it.

**Comment by MartinThoma** [comment]
I don't think this code change makes much sense. What does it improve? Which new functionality is added?

**Comment by sadaf2605** [comment]
Say we add a different script <code>training.py</code> now we need to call it from <code> evaluate.py</code> as <code>get_parser()</code> is in <code>evaluate.py</code>, so I am trying to call <code>get_parser()</code> from a neutral place like from <code>util.py</code> or <code>nntoolkit.py</code>, much like a controller in MVC arhitecture.

**Comment by MartinThoma** [comment]
Why should we have to call `get_parser` from anything else than `bin/nntoolkit`?

**Comment by sadaf2605** [comment]
Ow I did not notice that we have got a python script at `bin/nntoolkit`. But wait if we had it in `bin/nntoolkit` then why did we have the same script in `evaluate.py`?

**Comment by MartinThoma** [comment]
`bin/nntoolkit/` only handles the "general" argparser. The subcommands have to be registered there, but all handling of subcommands is done in the tools themselves.

For example, `nntoolkit/evaluate.py` and ``nntoolkit/create.py` provide different functionality and can be used independantly. They define which command line arguments they expect in their `get_parser` method:

```python
def get_parser():
    """Return the parser object for this script."""
    from argparse import ArgumentParser, ArgumentDefaultsHelpFormatter
    parser = ArgumentParser(description=__doc__,
                            formatter_class=ArgumentDefaultsHelpFormatter)
    parser.add_argument("-m", "--model",
                        dest="modelfile",
                        help="where is the model file (.tar)?",
                        metavar="FILE",
                        type=lambda x: utils.is_valid_file(parser, x),
                        required=True)
    parser.add_argument("-i", "--input",
                        dest="inputvec",
                        help="""a file which contains an input vector
                               [[0.12, 0.312, 1.21 ...]]""",
                        metavar="FILE",
                        type=lambda x: utils.is_valid_file(parser, x),
                        required=True)
    return parser
```

In `bin/nntoolkit` they are only called, so that python can glue it together:

```python
from nntoolkit import evaluate

[...]
def main(args):
    if args.cmd == 'evaluate':
        evaluate.main(args.modelfile, args.inputvec)
    elif args.cmd == 'create':
        create.main(args.type, args.architecture)
    else:
        logging.warning("Subcommand '%s' not implemented.", args.cmds)
```

The `get_parser` method within `bin/nntoolkit` defines the parser of `nntoolkit`. This is the most complex parser in the sense that it has to take all other parsers of the subcommands (evaluate, train, create, - eventually show, analyze, ...).

**Comment by MartinThoma** [comment]
Have you installed `nntoolkit`?

Just try the following commands:

```text
$ nntoolkit --help    <- gives contents defined in bin/nntoolkit
$ nntoolkit evaluate --help  <- gives contents defined in nntoolkit/evaluate.py
```

It is unfortunate that `bin/nntoolkit` is not `bin/nntoolkit.py`. However, I did not find a way how to give it a `.py` extension and still be able to call it without `.py` extension from command line.

**Pull request closed without merging**
